name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports: 
          - 27017:27017
    steps:
      - uses: actions/checkout@v4

      # Backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: cd server && npm install

      - name: Run backend tests
        run: cd server && npm test

      # Frontend (build only, no tests)
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: cd client && npm install

      - name: Build frontend
        run: cd client && npm run build